--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: reservations_administrateur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_administrateur (
    membre_ptr_id bigint NOT NULL
);


--
-- Name: reservations_bloquer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_bloquer (
    id bigint NOT NULL,
    date date NOT NULL,
    heure_debut integer NOT NULL,
    duree integer NOT NULL,
    raison character varying(200) NOT NULL,
    terrain_id bigint NOT NULL,
    administrateur_id bigint NOT NULL,
    statut character varying(10) NOT NULL
);


--
-- Name: reservations_bloquer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_bloquer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_bloquer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_categorie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_categorie (
    id bigint NOT NULL,
    nom character varying(50) NOT NULL,
    age_min integer NOT NULL,
    age_max integer NOT NULL,
    sexe character varying(1) NOT NULL,
    annee_naissance_max integer,
    annee_naissance_min integer,
    categorie_inclus_id bigint
);


--
-- Name: reservations_categorie_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_categorie ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_categorie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_membre; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_membre (
    id bigint NOT NULL,
    numero_affiliation character varying(7) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100) NOT NULL,
    rue character varying(255) NOT NULL,
    code_postal character varying(10) NOT NULL,
    localite character varying(100) NOT NULL,
    gsm character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    classement character varying(10) NOT NULL,
    sexe character varying(1) NOT NULL,
    date_naissance date NOT NULL,
    en_ordre_cotisation boolean NOT NULL,
    user_id integer,
    date_dernier_paiement timestamp with time zone,
    date_echeance date,
    google_email character varying(254)
);


--
-- Name: reservations_membre_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_membre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_membre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_reserver; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_reserver (
    id bigint NOT NULL,
    date date NOT NULL,
    heure_debut integer NOT NULL,
    duree integer NOT NULL,
    terrain_id bigint NOT NULL,
    statut character varying(10) NOT NULL
);


--
-- Name: reservations_reserver_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_reserver ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reserver_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_reserver_membres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_reserver_membres (
    id bigint NOT NULL,
    reserver_id bigint NOT NULL,
    membre_id bigint NOT NULL
);


--
-- Name: reservations_reserver_membres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_reserver_membres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reserver_membres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_terrain; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reservations_terrain (
    id bigint NOT NULL,
    numero integer NOT NULL,
    surface character varying(50) NOT NULL
);


--
-- Name: reservations_terrain_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reservations_terrain ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_terrain_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add membre	10	add_membre
26	Can change membre	10	change_membre
27	Can delete membre	10	delete_membre
28	Can view membre	10	view_membre
29	Can add categorie	9	add_categorie
30	Can change categorie	9	change_categorie
31	Can delete categorie	9	delete_categorie
32	Can view categorie	9	view_categorie
33	Can add terrain	12	add_terrain
34	Can change terrain	12	change_terrain
35	Can delete terrain	12	delete_terrain
36	Can view terrain	12	view_terrain
37	Can add administrateur	7	add_administrateur
38	Can change administrateur	7	change_administrateur
39	Can delete administrateur	7	delete_administrateur
40	Can view administrateur	7	view_administrateur
41	Can add reserver	11	add_reserver
42	Can change reserver	11	change_reserver
43	Can delete reserver	11	delete_reserver
44	Can view reserver	11	view_reserver
45	Can add bloquer	8	add_bloquer
46	Can change bloquer	8	change_bloquer
47	Can delete bloquer	8	delete_bloquer
48	Can view bloquer	8	view_bloquer
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
11	pbkdf2_sha256$1200000$VK3AviCGWdxX7vBDZMnpyH$ncLwccVM1QrSFW0bdqbIa6V4RhcXUkMqNxslCzAPGtI=	\N	f	2000006	Camille	Dubois	camille.dubois@email.com	f	t	2026-04-20 19:40:09.096108+02
4	pbkdf2_sha256$1200000$u1vvChDOP6Mu8lbzFZVdlC$yj8YSDPyVzZUalvv7d74CkidYZSu1ylotqoysX/ypv4=	2026-04-20 19:40:29.487803+02	f	2000002			fouad.elkadouri140@gmail.com	f	t	2026-04-15 18:04:18.808095+02
8	pbkdf2_sha256$1200000$XtJc3xB9w1bcskV0jZPDL1$0KKfwS93N8RdPsj8vJBoaLsGK+GYz++/tVFTYygGbIY=	2026-04-21 18:25:01.994563+02	f	2000003	Lucas	Dupont	lucas.dupont@email.com	f	t	2026-04-20 19:40:07.923049+02
2	pbkdf2_sha256$1200000$dUWoWfairZfBLzD9CyPdpv$9kfG4lDspUJDmzw4N8a98dDuMLI1mZ5roV9cXPcVOWo=	2026-05-12 10:24:23.963614+02	f	1234567	Jean	Dupont	fouad.elkadouri140@gmail.com	f	t	2026-04-10 18:29:02.409389+02
12	pbkdf2_sha256$1200000$7emyI6kxBVhzS3C604fOyE$dm6lvkfFNRJi6+byP7KfLRaq1ySs82Qrg8/r0ROn5Zc=	2026-05-12 11:09:32.045452+02	f	2000007	Nathan	Petit	nathan.petit@email.com	f	t	2026-04-20 19:40:09.476955+02
13	pbkdf2_sha256$1200000$ULs3OqGKshniCS9zeuDZgE$sNrm/P5kyBoBHqHvZNro8xDhMtOYq5TS0CLZTstJnKo=	2026-05-12 18:20:10.339332+02	f	1000002	Carlos	Alcaraz	c.alcaraz@tennisclub.be	f	t	2026-05-12 18:20:09.214817+02
3	pbkdf2_sha256$1200000$lSzh3zho2nGsFsi1U9VaT8$73+Y0z/JFKF1BMu5Wu034GWkuVEBC+CQ7uwl25PGzoY=	2026-05-15 17:15:46.123716+02	f	1234568	Jean	Dupont	fouad.elkadouri140@gmail.com	f	t	2026-04-15 18:04:18.407748+02
6	pbkdf2_sha256$1200000$JtzEqgyZg1yqFMmabr4kSV$Z6fSkKqXI5HOfX63jMjwbY3W/VBBxR+lhNXTIu7l1ng=	2026-04-18 13:07:27.654976+02	f	1234569	Claire	Flamend	Claire.flamend@gmail.com	f	t	2026-04-18 12:35:10.60066+02
1	pbkdf2_sha256$1200000$5CG0Erl85xVS5mkTED3vdC$DGUQXF3rgls4xhq9at11F/LTUDWWF1jhdqjD4z65yD8=	2026-04-10 18:18:18.75258+02	t	fek			fouad.elkadouri140@gmail.com	t	t	2026-04-01 19:21:51.605152+02
5	pbkdf2_sha256$1200000$UDw3FdtsXQ62jfU3OlqgAO$qYgfTf67RmEM7UT0Czt9x+AGP9G1h+97FWkQqFpcK9s=	\N	f	3000003			fouad.elkadouri140@gmail.com	f	t	2026-04-15 18:04:19.19821+02
9	pbkdf2_sha256$1200000$bMCpqPZpiZzSrNt6hHjS74$auf8btVkVe9CSUvpK5UpkEJeLRZ9kLWPAO9f2gn6YgE=	2026-04-24 18:19:17.317305+02	f	2000004	Emma	Martin	emma.martin@email.com	f	t	2026-04-20 19:40:08.317222+02
10	pbkdf2_sha256$1200000$XHGtKfpQIevr6cCfxc2mRJ$JJgy5ISdSi28q0MoOEn5h2H49bHR+kAJNFx+VzjfeYE=	2026-04-24 18:19:31.682744+02	f	2000005	Thomas	Leroy	thomas.leroy@email.com	f	t	2026-04-20 19:40:08.704105+02
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-01 20:15:42.485568+02	1	Adulte (18-100 ans)	1	[{"added": {}}]	9	1
2	2026-04-01 20:16:16.575862+02	1	Terrain 1	1	[{"added": {}}]	12	1
3	2026-04-01 20:16:28.042229+02	1	Terrain 1	3		12	1
4	2026-04-01 20:18:00.718067+02	1	Adulte (18-100 ans)	3		9	1
5	2026-04-10 18:27:09.730769+02	4	Jean Dupont	1	[{"added": {}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	reservations	administrateur
8	reservations	bloquer
9	reservations	categorie
10	reservations	membre
11	reservations	reserver
12	reservations	terrain
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-01 17:38:49.016111+02
2	auth	0001_initial	2026-04-01 17:38:49.060478+02
3	admin	0001_initial	2026-04-01 17:38:49.072634+02
4	admin	0002_logentry_remove_auto_add	2026-04-01 17:38:49.07685+02
5	admin	0003_logentry_add_action_flag_choices	2026-04-01 17:38:49.080223+02
6	contenttypes	0002_remove_content_type_name	2026-04-01 17:38:49.087874+02
7	auth	0002_alter_permission_name_max_length	2026-04-01 17:38:49.092364+02
8	auth	0003_alter_user_email_max_length	2026-04-01 17:38:49.096179+02
9	auth	0004_alter_user_username_opts	2026-04-01 17:38:49.103131+02
10	auth	0005_alter_user_last_login_null	2026-04-01 17:38:49.107577+02
11	auth	0006_require_contenttypes_0002	2026-04-01 17:38:49.108437+02
12	auth	0007_alter_validators_add_error_messages	2026-04-01 17:38:49.112052+02
13	auth	0008_alter_user_username_max_length	2026-04-01 17:38:49.118496+02
14	auth	0009_alter_user_last_name_max_length	2026-04-01 17:38:49.123224+02
15	auth	0010_alter_group_name_max_length	2026-04-01 17:38:49.127851+02
16	auth	0011_update_proxy_permissions	2026-04-01 17:38:49.131272+02
17	auth	0012_alter_user_first_name_max_length	2026-04-01 17:38:49.135186+02
18	reservations	0001_initial	2026-04-01 17:38:49.177926+02
19	sessions	0001_initial	2026-04-01 17:38:49.184248+02
20	reservations	0002_terrain_surface	2026-04-01 20:48:55.606623+02
21	reservations	0003_alter_administrateur_options_and_more	2026-04-03 18:41:17.789251+02
22	reservations	0004_remove_membre_categorie_and_more	2026-04-03 19:22:58.623461+02
23	reservations	0005_bloquer_statut_categorie_annee_naissance_max_and_more	2026-04-10 17:51:17.400754+02
24	reservations	0006_alter_membre_user	2026-04-10 18:27:01.316574+02
25	reservations	0007_membre_date_dernier_paiement_membre_date_echeance_and_more	2026-04-15 11:15:54.244121+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
34lqt36nuaqf3ksav41duzicq7kog0c7	.eJxVjLsOwjAMAP_FM4oSt7RJR_Z-Q2XHDimgROpjQvw7qtQB1rvTvWGifcvTvuoyzQIDtHD5ZUzxqeUQ8qByrybWsi0zmyMxp13NWEVft7P9G2RaMwxgnQTtorvarmElZ0PS0CdECpQsS4eRk0cVRkqCjetRCD0yesctKny--GY4eA:1wD3yO:MVzp-Qhp9vlSpdQwQqPJ8cYJpEJm6l1DWx6Tup9-bkg	2026-04-29 19:24:20.802078+02
otpijj9hnxxjtg09y4id9pxhf3ucepjm	.eJxVjLsOwjAMAP_FM4oSt7RJR_Z-Q2XHDimgROpjQvw7qtQB1rvTvWGifcvTvuoyzQIDtHD5ZUzxqeUQ8qByrybWsi0zmyMxp13NWEVft7P9G2RaMwxgnQTtorvarmElZ0PS0CdECpQsS4eRk0cVRkqCjetRCD0yesctKny--GY4eA:1wE38c:wDh6-z9zA-uA1QcorKKpNwS9uFRN9UmOKZRj0ta4fJ0	2026-05-02 12:42:58.582325+02
ti2ydzt2hdajh7zek23eaus8vg0kkztn	.eJxVjLsKwzAMAP9FczGyHb8ydu83BEUSddqSQJxMpf9eAhna9e64Nwy0b3XYm67DJNCDhcsvG4mfOh9CHjTfF8PLvK3TaI7EnLaZ2yL6up7t36BSq9BDURYfPWIXbMaUsyJryjFTKNRlksCUiqKIhIjkOm-jjcguOvWECJ8vyTA3BQ:1wBEYk:rA21ZGS221I0LODrPDZqV5kmBWb9juKk7l5KQABVcD0	2026-04-24 18:18:18.753952+02
d8nbhxslu6gl7glp7zjrv888qnxb35a5	.eJxVjDkOwjAQAP-yNbK8vpOSnjdYuz5wACVSnFSIv6NIKaCdGc0bIu1bi3sva5wyjKDg8suY0rPMh8gPmu-LSMu8rROLIxGn7eK25PK6nu3foFFvMAJ5UoRoKAzktAtctcqcAhu2FKytipM1FauXqKTP2ngnUeJA6AeHGj5f4FY2-w:1wD2g6:ahQwCplKW1Y21a9HxiYNEUCroEgscIftrwu8mv2CXxs	2026-04-29 18:01:22.174612+02
6fo1bkuyiwkb4euhf3750homr3i3ydbx	.eJxVjDEOgzAMAP_iuYoMIUnN2J03INsxhbYCicBU9e8VEkO73p3uDT3v29jvxdZ-ytCCh8svE9anzYfID57vi9Nl3tZJ3JG40xbXLdlet7P9G4xcRmgBMVFOqkiE9VUFBwrs_aAxCkuT6sqCTxyDGlfBq7FRQCRpUKjOET5f3G83yA:1wNuGQ:_PETQCZ0SccuGWdnpilt00VMjpsqK-5VpMFaSXpmR4s	2026-05-29 17:15:46.129477+02
pjpdn2bwrr0udpoz90i8e65xkl4afpdh	.eJxVjLsOwjAMAP_FM4oSt7RJR_Z-Q2XHDimgROpjQvw7qtQB1rvTvWGifcvTvuoyzQIDtHD5ZUzxqeUQ8qByrybWsi0zmyMxp13NWEVft7P9G2RaMwxgnQTtorvarmElZ0PS0CdECpQsS4eRk0cVRkqCjetRCD0yesctKny--GY4eA:1wD3wS:qQfwn8mUXNhZFwEMuKfQk4R7LxaeKE2YSeoupllqYpI	2026-04-29 19:22:20.268016+02
\.


--
-- Data for Name: reservations_administrateur; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_administrateur (membre_ptr_id) FROM stdin;
5
\.


--
-- Data for Name: reservations_bloquer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_bloquer (id, date, heure_debut, duree, raison, terrain_id, administrateur_id, statut) FROM stdin;
1	2026-04-16	10	2	Entretien	3	5	bloque
2	2026-05-22	12	1	Tournoi Mai 2026	4	5	bloque
\.


--
-- Data for Name: reservations_categorie; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_categorie (id, nom, age_min, age_max, sexe, annee_naissance_max, annee_naissance_min, categorie_inclus_id) FROM stdin;
1	Junior Garçons	5	12	M	\N	\N	\N
2	Junior Filles	5	12	F	\N	\N	\N
3	Messieurs Adultes	13	99	M	\N	\N	\N
4	Dames Adultes	13	99	F	\N	\N	\N
5	Messieurs	18	99	M	\N	\N	\N
6	Messieurs 35	35	99	M	\N	\N	\N
7	Messieurs 45	45	99	M	\N	\N	\N
8	Messieurs 55	55	99	M	\N	\N	\N
9	Messieurs 65	65	99	M	\N	\N	\N
10	Juniors garcons 18	15	18	M	\N	\N	\N
11	Juniors garcons 15	13	15	M	\N	\N	\N
12	Juniors garcons 13	11	13	M	\N	\N	\N
13	Juniors garcons 11	9	11	M	\N	\N	\N
14	Dames	18	99	F	\N	\N	\N
15	Dames 35	35	99	F	\N	\N	\N
16	Dames 45	45	99	F	\N	\N	\N
17	Dames 55	55	99	F	\N	\N	\N
18	Dames 65	65	99	F	\N	\N	\N
19	Juniors filles 18	15	18	F	\N	\N	\N
20	Juniors filles 15	13	15	F	\N	\N	\N
21	Juniors filles 13	11	13	F	\N	\N	\N
22	Juniors filles 11	9	11	F	\N	\N	\N
\.


--
-- Data for Name: reservations_membre; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_membre (id, numero_affiliation, nom, prenom, rue, code_postal, localite, gsm, email, classement, sexe, date_naissance, en_ordre_cotisation, user_id, date_dernier_paiement, date_echeance, google_email) FROM stdin;
1	1000001	Lemaire	Thomas	Rue de la Paix 10	4800	Verviers	0470123456	t.lemaire@email.com	B-15	M	1995-03-12	t	\N	\N	\N	\N
4	1234567	Dupont	Jean	rue de Test 1	4000	Liège	04711234567	jean@test.be	N.C	M	1990-01-01	t	2	\N	2027-01-01	\N
3	3000003	Mertens	David	Rue du Palais 4	4800	Verviers	0499001122	d.mertens@email.com	N.C	M	2012-05-20	t	5	\N	2027-01-01	\N
12	1000002	Alcaraz	Carlos	1 Rue du Tennis	1000	Liège	0470000001	c.alcaraz@tennisclub.be	A	M	2003-05-16	t	13	2026-05-12 18:41:23.250337+02	2027-05-12	fouad.elkadouri140@gmail.com
5	1234568	Dupont	Jean	rue de Test 1	4000	Liège	04711234567	admin@tennisclub.be	B15	M	1990-05-15	t	3	\N	2027-01-01	\N
6	1234569	Flamend	Claire	de Dison 16	4800	Verviers	0495856566	Claire.flamend@gmail.com	N.C	F	2004-01-01	t	6	2026-04-18 13:07:56.061806+02	2027-04-18	fouad.elkadouri140@gmail.com
10	2000006	Dubois	Camille	Grand Place 7	7000	Mons	0474000006	camille.dubois@email.com	B+2/6	F	1995-01-30	f	11	\N	\N	
2	2000002	Gérard	Sophie	Avenue des Sports 5	4000	Liège	0480987654	s.gerard@email.com	C30.2	F	1988-11-25	t	4	2026-04-20 19:40:53.091069+02	2027-04-20	fouad.elkadouri140@gmail.com
7	2000003	Dupont	Lucas	Rue Neuve 10	1000	Bruxelles	0471000003	lucas.dupont@email.com	C30	M	2001-03-15	t	8	2026-04-20 19:42:10.089835+02	2027-04-20	fouad.elkadouri140@gmail.com
8	2000004	Martin	Emma	Boulevard Avroy 5	4000	Liege	0472000004	emma.martin@email.com	C15.2	F	1998-07-22	t	9	\N	\N	
9	2000005	Leroy	Thomas	Place dArmes 3	5000	Namur	0473000005	thomas.leroy@email.com	N.C	M	2003-11-08	t	10	2026-04-24 18:20:48.553816+02	2027-04-24	fouad.elkadouri140@gmail.com
11	2000007	Petit	Nathan	Rue de Marcinelle 12	6000	Charleroi	0475000007	nathan.petit@email.com	C30.3	M	2000-09-12	f	12	\N	\N	fouad.elkadouri140@gmail.com
13	1000003	Sinner	Jannik	1 Rue du Tennis	9000	Gand	0470000002	j.sinner@tennisclub.be	A	M	2001-08-16	f	\N	\N	\N	\N
14	1000004	Medvedev	Daniil	1 Rue du Tennis	5000	Namur	0470000003	d.medvedev@tennisclub.be	A	M	1996-02-11	f	\N	\N	\N	\N
15	1000005	Zverev	Alexander	1 Rue du Tennis	8000	Bruges	0470000004	a.zverev@tennisclub.be	A	M	1997-04-20	f	\N	\N	\N	\N
16	1000006	Tsitsipas	Stefanos	1 Rue du Tennis	7000	Mons	0470000005	s.tsitsipas@tennisclub.be	A	M	1998-08-12	f	\N	\N	\N	\N
17	1000007	Djokovic	Novak	1 Rue du Tennis	1000	Bruxelles	0470000006	n.djokovic@tennisclub.be	A	M	1987-05-22	f	\N	\N	\N	\N
18	1000008	Rublev	Andrey	1 Rue du Tennis	6000	Charleroi	0470000007	a.rublev@tennisclub.be	B15	M	1997-10-20	f	\N	\N	\N	\N
19	1000009	Hurkacz	Hubert	1 Rue du Tennis	2000	Anvers	0470000008	h.hurkacz@tennisclub.be	B15	M	1997-02-11	f	\N	\N	\N	\N
20	1000010	Fritz	Taylor	1 Rue du Tennis	3000	Louvain	0470000009	t.fritz@tennisclub.be	B15	M	1997-10-28	f	\N	\N	\N	\N
21	1000011	Ruud	Casper	1 Rue du Tennis	3500	Hasselt	0470000010	c.ruud@tennisclub.be	B15	M	1998-12-22	f	\N	\N	\N	\N
22	1000012	Dimitrov	Grigor	1 Rue du Tennis	7500	Tournai	0470000011	g.dimitrov@tennisclub.be	B0	M	1991-05-16	f	\N	\N	\N	\N
23	1000013	Auger	Felix	1 Rue du Tennis	4800	Verviers	0470000012	f.auger@tennisclub.be	B0	M	2000-08-08	f	\N	\N	\N	\N
24	1000014	Tiafoe	Frances	1 Rue du Tennis	8400	Ostende	0470000013	f.tiafoe@tennisclub.be	B0	M	1998-01-20	f	\N	\N	\N	\N
25	1000015	Paul	Tommy	1 Rue du Tennis	4000	Liège	0470000014	t.paul@tennisclub.be	B0	M	1997-05-17	f	\N	\N	\N	\N
26	1000016	Khachanov	Karen	1 Rue du Tennis	1000	Bruxelles	0470000015	k.khachanov@tennisclub.be	B-2/6	M	1996-05-21	f	\N	\N	\N	\N
27	1000017	Korda	Sebastian	1 Rue du Tennis	5000	Namur	0470000016	s.korda@tennisclub.be	B-2/6	M	2000-07-05	f	\N	\N	\N	\N
28	1000018	Shelton	Ben	1 Rue du Tennis	9000	Gand	0470000017	b.shelton@tennisclub.be	B-2/6	M	2002-10-09	f	\N	\N	\N	\N
29	1000019	Norrie	Cameron	1 Rue du Tennis	8000	Bruges	0470000018	c.norrie@tennisclub.be	C15	M	1995-08-23	f	\N	\N	\N	\N
30	1000020	Cerundolo	Francisco	1 Rue du Tennis	7000	Mons	0470000019	f.cerundolo@tennisclub.be	C15	M	1998-08-06	f	\N	\N	\N	\N
31	1000021	Musetti	Lorenzo	1 Rue du Tennis	2000	Anvers	0470000020	l.musetti@tennisclub.be	C15	M	2002-03-03	f	\N	\N	\N	\N
32	1000022	Berrettini	Matteo	1 Rue du Tennis	3000	Louvain	0470000021	m.berrettini@tennisclub.be	C15	M	1996-04-12	f	\N	\N	\N	\N
33	1000023	Draper	Jack	1 Rue du Tennis	3500	Hasselt	0470000022	j.draper@tennisclub.be	C30	M	2001-09-22	f	\N	\N	\N	\N
34	1000024	Baez	Sebastian	1 Rue du Tennis	7500	Tournai	0470000023	s.baez@tennisclub.be	C30	M	2000-10-19	f	\N	\N	\N	\N
35	1000025	Lehecka	Jiri	1 Rue du Tennis	4800	Verviers	0470000024	j.lehecka@tennisclub.be	C30	M	2001-07-26	f	\N	\N	\N	\N
36	2000008	Swiatek	Iga	1 Rue du Tennis	1000	Bruxelles	0470000025	i.swiatek@tennisclub.be	A	F	2001-05-31	f	\N	\N	\N	\N
37	2000009	Sabalenka	Aryna	1 Rue du Tennis	4000	Liège	0470000026	a.sabalenka@tennisclub.be	A	F	1998-05-05	f	\N	\N	\N	\N
38	2000010	Gauff	Coco	1 Rue du Tennis	9000	Gand	0470000027	c.gauff@tennisclub.be	A	F	2004-03-13	f	\N	\N	\N	\N
39	2000011	Rybakina	Elena	1 Rue du Tennis	5000	Namur	0470000028	e.rybakina@tennisclub.be	A	F	1999-06-17	f	\N	\N	\N	\N
40	2000012	Pegula	Jessica	1 Rue du Tennis	8000	Bruges	0470000029	j.pegula@tennisclub.be	A	F	1994-02-24	f	\N	\N	\N	\N
41	2000013	Sakkari	Maria	1 Rue du Tennis	7000	Mons	0470000030	m.sakkari@tennisclub.be	B15	F	1995-07-26	f	\N	\N	\N	\N
42	2000014	Jabeur	Ons	1 Rue du Tennis	6000	Charleroi	0470000031	o.jabeur@tennisclub.be	B15	F	1994-08-28	f	\N	\N	\N	\N
43	2000015	Collins	Danielle	1 Rue du Tennis	2000	Anvers	0470000032	d.collins@tennisclub.be	B15	F	1994-12-13	f	\N	\N	\N	\N
44	2000016	Kvitova	Petra	1 Rue du Tennis	3000	Louvain	0470000033	p.kvitova@tennisclub.be	B15	F	1990-03-08	f	\N	\N	\N	\N
45	2000017	Halep	Simona	1 Rue du Tennis	3500	Hasselt	0470000034	s.halep@tennisclub.be	B0	F	1991-09-27	f	\N	\N	\N	\N
46	2000018	Badosa	Paula	1 Rue du Tennis	7500	Tournai	0470000035	p.badosa@tennisclub.be	B0	F	1997-11-15	f	\N	\N	\N	\N
47	2000019	Azarenka	Victoria	1 Rue du Tennis	4800	Verviers	0470000036	v.azarenka@tennisclub.be	B0	F	1989-07-31	f	\N	\N	\N	\N
48	2000020	Haddad	Beatriz	1 Rue du Tennis	8400	Ostende	0470000037	b.haddad@tennisclub.be	B-2/6	F	1996-05-30	f	\N	\N	\N	\N
49	2000021	Ostapenko	Jelena	1 Rue du Tennis	1000	Bruxelles	0470000038	j.ostapenko@tennisclub.be	B-2/6	F	1997-06-08	f	\N	\N	\N	\N
50	2000022	Vondrousova	Marketa	1 Rue du Tennis	4000	Liège	0470000039	m.vondrousova@tennisclub.be	B-2/6	F	1999-06-28	f	\N	\N	\N	\N
\.


--
-- Data for Name: reservations_reserver; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_reserver (id, date, heure_debut, duree, terrain_id, statut) FROM stdin;
1	2026-04-03	13	1	1	libre
2	2026-04-03	9	1	1	libre
3	2026-04-03	10	1	1	libre
4	2026-04-03	10	1	2	libre
5	2026-04-03	11	1	2	libre
6	2026-04-12	9	1	3	libre
7	2026-04-08	10	1	3	libre
8	2026-04-08	11	1	3	libre
9	2026-04-10	9	1	2	reserve
10	2026-04-16	10	1	1	reserve
12	2026-04-14	16	1	1	reserve
13	2026-04-15	20	1	1	reserve
14	2026-04-20	10	1	2	reserve
16	2026-04-23	19	1	3	reserve
18	2026-04-25	11	2	3	reserve
\.


--
-- Data for Name: reservations_reserver_membres; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_reserver_membres (id, reserver_id, membre_id) FROM stdin;
1	1	1
2	1	2
3	2	1
4	2	2
5	2	3
6	3	2
7	3	3
8	4	2
9	5	1
10	5	2
11	6	1
12	6	2
13	6	3
14	7	1
15	7	2
16	8	1
17	8	2
18	8	3
19	9	3
20	9	4
21	10	3
22	10	4
24	12	3
25	12	4
26	13	1
27	13	2
28	14	3
29	14	4
32	16	1
33	16	4
36	18	8
37	18	2
38	18	7
39	18	9
\.


--
-- Data for Name: reservations_terrain; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.reservations_terrain (id, numero, surface) FROM stdin;
1	1	Terre Battue
2	2	Terre Battue
3	3	Synthétique
4	4	Quick (Indoor)
5	5	Quick (Indoor)
6	6	Terre Battue
7	7	Gazon
8	8	Gazon
9	9	Dur
10	10	Dur
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 13, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 5, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: reservations_bloquer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_bloquer_id_seq', 2, true);


--
-- Name: reservations_categorie_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_categorie_id_seq', 22, true);


--
-- Name: reservations_membre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_membre_id_seq', 206, true);


--
-- Name: reservations_reserver_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_reserver_id_seq', 18, true);


--
-- Name: reservations_reserver_membres_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_reserver_membres_id_seq', 39, true);


--
-- Name: reservations_terrain_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.reservations_terrain_id_seq', 14, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: reservations_administrateur reservations_administrateur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_administrateur
    ADD CONSTRAINT reservations_administrateur_pkey PRIMARY KEY (membre_ptr_id);


--
-- Name: reservations_bloquer reservations_bloquer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_bloquer
    ADD CONSTRAINT reservations_bloquer_pkey PRIMARY KEY (id);


--
-- Name: reservations_categorie reservations_categorie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_categorie
    ADD CONSTRAINT reservations_categorie_pkey PRIMARY KEY (id);


--
-- Name: reservations_membre reservations_membre_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_membre
    ADD CONSTRAINT reservations_membre_email_key UNIQUE (email);


--
-- Name: reservations_membre reservations_membre_numero_affiliation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_membre
    ADD CONSTRAINT reservations_membre_numero_affiliation_key UNIQUE (numero_affiliation);


--
-- Name: reservations_membre reservations_membre_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_membre
    ADD CONSTRAINT reservations_membre_pkey PRIMARY KEY (id);


--
-- Name: reservations_membre reservations_membre_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_membre
    ADD CONSTRAINT reservations_membre_user_id_key UNIQUE (user_id);


--
-- Name: reservations_reserver_membres reservations_reserver_me_reserver_id_membre_id_ff561ff7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver_membres
    ADD CONSTRAINT reservations_reserver_me_reserver_id_membre_id_ff561ff7_uniq UNIQUE (reserver_id, membre_id);


--
-- Name: reservations_reserver_membres reservations_reserver_membres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver_membres
    ADD CONSTRAINT reservations_reserver_membres_pkey PRIMARY KEY (id);


--
-- Name: reservations_reserver reservations_reserver_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver
    ADD CONSTRAINT reservations_reserver_pkey PRIMARY KEY (id);


--
-- Name: reservations_terrain reservations_terrain_numero_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_terrain
    ADD CONSTRAINT reservations_terrain_numero_key UNIQUE (numero);


--
-- Name: reservations_terrain reservations_terrain_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_terrain
    ADD CONSTRAINT reservations_terrain_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: reservations_bloquer_administrateur_id_d90883ac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_bloquer_administrateur_id_d90883ac ON public.reservations_bloquer USING btree (administrateur_id);


--
-- Name: reservations_bloquer_terrain_id_69a7dbb0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_bloquer_terrain_id_69a7dbb0 ON public.reservations_bloquer USING btree (terrain_id);


--
-- Name: reservations_categorie_categorie_inclus_id_076d55fa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_categorie_categorie_inclus_id_076d55fa ON public.reservations_categorie USING btree (categorie_inclus_id);


--
-- Name: reservations_membre_email_c9e52c9a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_membre_email_c9e52c9a_like ON public.reservations_membre USING btree (email varchar_pattern_ops);


--
-- Name: reservations_membre_numero_affiliation_ffdbd26f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_membre_numero_affiliation_ffdbd26f_like ON public.reservations_membre USING btree (numero_affiliation varchar_pattern_ops);


--
-- Name: reservations_reserver_membres_membre_id_62beca14; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_reserver_membres_membre_id_62beca14 ON public.reservations_reserver_membres USING btree (membre_id);


--
-- Name: reservations_reserver_membres_reserver_id_bce2c90c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_reserver_membres_reserver_id_bce2c90c ON public.reservations_reserver_membres USING btree (reserver_id);


--
-- Name: reservations_reserver_terrain_id_d95788f2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX reservations_reserver_terrain_id_d95788f2 ON public.reservations_reserver USING btree (terrain_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_administrateur reservations_adminis_membre_ptr_id_5e6b4c97_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_administrateur
    ADD CONSTRAINT reservations_adminis_membre_ptr_id_5e6b4c97_fk_reservati FOREIGN KEY (membre_ptr_id) REFERENCES public.reservations_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_bloquer reservations_bloquer_administrateur_id_d90883ac_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_bloquer
    ADD CONSTRAINT reservations_bloquer_administrateur_id_d90883ac_fk_reservati FOREIGN KEY (administrateur_id) REFERENCES public.reservations_administrateur(membre_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_bloquer reservations_bloquer_terrain_id_69a7dbb0_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_bloquer
    ADD CONSTRAINT reservations_bloquer_terrain_id_69a7dbb0_fk_reservati FOREIGN KEY (terrain_id) REFERENCES public.reservations_terrain(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_categorie reservations_categor_categorie_inclus_id_076d55fa_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_categorie
    ADD CONSTRAINT reservations_categor_categorie_inclus_id_076d55fa_fk_reservati FOREIGN KEY (categorie_inclus_id) REFERENCES public.reservations_categorie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_membre reservations_membre_user_id_7a47f351_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_membre
    ADD CONSTRAINT reservations_membre_user_id_7a47f351_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reserver_membres reservations_reserve_membre_id_62beca14_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver_membres
    ADD CONSTRAINT reservations_reserve_membre_id_62beca14_fk_reservati FOREIGN KEY (membre_id) REFERENCES public.reservations_membre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reserver_membres reservations_reserve_reserver_id_bce2c90c_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver_membres
    ADD CONSTRAINT reservations_reserve_reserver_id_bce2c90c_fk_reservati FOREIGN KEY (reserver_id) REFERENCES public.reservations_reserver(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reserver reservations_reserve_terrain_id_d95788f2_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reservations_reserver
    ADD CONSTRAINT reservations_reserve_terrain_id_d95788f2_fk_reservati FOREIGN KEY (terrain_id) REFERENCES public.reservations_terrain(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

