# Generated by Django 6.0.3 on 2026-04-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_affiliation', models.CharField(max_length=7, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('rue', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('localite', models.CharField(max_length=100)),
                ('gsm', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('classement', models.CharField(choices=[('A', 'A'), ('B-15.4', 'B-15.4'), ('B-15.2', 'B-15.2'), ('B-15.1', 'B-15.1'), ('B-15', 'B-15'), ('B-4/6', 'B-4/6'), ('B-2/6', 'B-2/6'), ('B0', 'B0'), ('B+2/6', 'B+2/6'), ('B+4/6', 'B+4/6'), ('C15', 'C15'), ('C15.1', 'C15.1'), ('C15.2', 'C15.2'), ('C15.3', 'C15.3'), ('C15.4', 'C15.4'), ('C30', 'C30'), ('C30.1', 'C30.1'), ('C30.2', 'C30.2'), ('C30.3', 'C30.3'), ('C30.4', 'C30.4'), ('C30.5', 'C30.5'), ('N.C', 'N.C')], default='N.C', max_length=10)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('est_actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('age_min', models.IntegerField()),
                ('age_max', models.IntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.membre')),
            ],
            bases=('reservations.membre',),
        ),
        migrations.AddField(
            model_name='membre',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.categorie'),
        ),
        migrations.CreateModel(
            name='Reserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.IntegerField(choices=[(9, '9h00'), (10, '10h00'), (11, '11h00'), (12, '12h00'), (13, '13h00'), (14, '14h00'), (15, '15h00'), (16, '16h00'), (17, '17h00'), (18, '18h00'), (19, '19h00'), (20, '20h00'), (21, '21h00'), (22, '22h00')])),
                ('duree', models.IntegerField(default=1)),
                ('membres', models.ManyToManyField(to='reservations.membre')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bloquer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.IntegerField(choices=[(9, '9h00'), (10, '10h00'), (11, '11h00'), (12, '12h00'), (13, '13h00'), (14, '14h00'), (15, '15h00'), (16, '16h00'), (17, '17h00'), (18, '18h00'), (19, '19h00'), (20, '20h00'), (21, '21h00'), (22, '22h00')])),
                ('duree', models.IntegerField(default=1)),
                ('raison', models.CharField(max_length=200)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.terrain')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.administrateur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
