# Generated by Django 6.0.3 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='surface',
            field=models.CharField(default='Terre Battue', max_length=50),
        ),
    ]
