# Generated by Django 6.0.3 on 2026-04-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_terrain_surface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrateur',
            options={'verbose_name': 'Administrateur'},
        ),
        migrations.RenameField(
            model_name='membre',
            old_name='est_actif',
            new_name='en_ordre_cotisation',
        ),
        migrations.AddField(
            model_name='membre',
            name='est_administrateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloquer',
            name='heure_debut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='sexe',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='membre',
            name='classement',
            field=models.CharField(choices=[('A', 'A'), ('B0', 'B0'), ('C15', 'C15'), ('C30', 'C30'), ('N.C', 'N.C')], default='N.C', max_length=10),
        ),
        migrations.AlterField(
            model_name='membre',
            name='sexe',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='reserver',
            name='heure_debut',
            field=models.IntegerField(),
        ),
    ]
