# Generated by Django 6.0.3 on 2026-04-03 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_administrateur_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='est_administrateur',
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
