# Generated by Django 6.0.3 on 2026-04-10 15:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_membre_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloquer',
            name='statut',
            field=models.CharField(choices=[('libre', 'Libre'), ('reserve', 'Réservé'), ('bloque', 'Bloqué')], default='libre', max_length=10),
        ),
        migrations.AddField(
            model_name='categorie',
            name='annee_naissance_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='annee_naissance_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_inclus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.categorie'),
        ),
        migrations.AddField(
            model_name='reserver',
            name='statut',
            field=models.CharField(choices=[('libre', 'Libre'), ('reserve', 'Réservé'), ('bloque', 'Bloqué')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='membre',
            name='classement',
            field=models.CharField(choices=[('A', 'A'), ('B-15.4', 'B-15.4'), ('B-15.2', 'B-15.2'), ('B-15.1', 'B-15.1'), ('B15', 'B15'), ('B-4/6', 'B-4/6'), ('B-2/6', 'B-2/6'), ('B0', 'B0'), ('B+2/6', 'B+2/6'), ('B+4/6', 'B+4/6'), ('C15', 'C15'), ('C15.1', 'C15.1'), ('C15.2', 'C15.2'), ('C15.3', 'C15.3'), ('C15.4', 'C15.4'), ('C30', 'C30'), ('C30.1', 'C30.1'), ('C30.2', 'C30.2'), ('C30.3', 'C30.3'), ('C30.4', 'C30.4'), ('C30.5', 'C30.5'), ('N.C', 'N.C')], default='N.C', max_length=10),
        ),
        migrations.AlterField(
            model_name='membre',
            name='numero_affiliation',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="Le numéro d'affiliation doit faire 7 chiffres et ne pas commencer par 0.", regex='^[1-9]\\d{6}$')]),
        ),
    ]
