# Generated by Django 6.0.3 on 2026-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_membre_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_dernier_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
